[package]
name = 'MovementDEXLP'
version = '1.0.0'

[addresses]
movement_dex_lp = "0x5a33c876cbc9c16d0a8d030c21f279d8e34682cd8014200b7d93fedba0e7ffa3"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/move-stdlib"
